### ISSUE TITLE
how to handle keyboard "Done" button in iphone safari browser?

### ISSUE THREAD

**Issue by ramkumarramaraj** [kabirbaidhya/keycode-js#13]

**Comment by mesaugat** [comment]
Hello @ramkumarramaraj,

This package only exports [key code constants](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#Constants_for_keyCode_value) for different keys.

How to handle keyboard events is completely up to you. Also, respective vendors send keycode events differently. Please refer to the vendor specific documentation for cases like these. `StackOverflow` can help in these situations.

Here is one answer I found:

`The done key is the same as the enter key.`

https://stackoverflow.com/questions/4971061/capture-done-button-click-in-iphones-virtual-keyboard-with-javascript

You'll probably need to addEventListeners for `change`, `focusout` and `blur`. See the answer for more details.
