### ISSUE TITLE
KEY_ENTER = 14 ? Not a 13?

### ISSUE THREAD

**Issue by denisx** [kabirbaidhya/keycode-js#14]

**Comment by mesaugat** [comment]
Take a look here. 

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#Constants_for_keyCode_value

<img width="1060" alt="screen shot 2018-12-10 at 2 20 20 pm" src="https://user-images.githubusercontent.com/4240991/49719978-d0945780-fc86-11e8-8314-d095bd0c1aa3.png">

Not to confuse, the `KEY_ENTER` you are referring to is `KEY_RETURN`.
