### ISSUE TITLE
The Key 193 is not present

### ISSUE THREAD

**Issue by carlosrodj** [kabirbaidhya/keycode-js#16]
Hello, in your package the 193 key is not intended as a domain, could you insert it? Can I perform a PR for correction, is it possible?

**Comment by mesaugat** [comment]
Hello @carlosrodj, thank you for creating an issue. 

> the 193 key is not intended as a domain

Which key are you referring to? Domain?

**Comment by kabirbaidhya** [comment]
@carlosrodj I couldn't find the key code 193 in the list of key code constants [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#Constants_for_keyCode_value) as per Mozilla either. 

We're not aware about this key, is this documented somewhere?

**Comment by carlosrodj** [comment]
using console.log in the key ID, it would be "/" which at least on my computer is not identified.

**Comment by kabirbaidhya** [comment]
@carlosrodj I couldn't find it in the w3c based list [here](https://lists.w3.org/Archives/Public/www-dom/2010JulSep/att-0182/keyCode-spec.html) too - you can see "/" is `191`. 

Which keyboard are you using?

**Comment by carlosrodj** [comment]
If there is a problem, you can choose a specific issue for yourself, especially if you have a particular problem.

Ty!

**Comment by mesaugat** [comment]
@carlosrodj Not sure what you are referring to. 

If you can tell us which keyboard you are using, we might be able to help. This might be an issue for other users too.
