### ISSUE TITLE
Replace webpack with rollup

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/keycode-js#3]
Currently, it's using `webpack` to bundle things up need to use `rollup` instead.

**Comment by mesaugat** [comment]
Let me try this.

**Comment by kabirbaidhya** [comment]
Sure :+1:. I think you can try this https://github.com/kabirbaidhya/keycode-js/issues/5 export thing too :wink:

**Comment by kabirbaidhya** [comment]
@mesaugat I think we need neither webpack nor rollup for this as this is just a single file, why do we even require bundling :smile:. I think we can rewrite this in typescript, it would generate `.d.ts` too.

**Comment by mesaugat** [comment]
For the browser?

**Comment by kabirbaidhya** [comment]
For browser, we need to minify the es5 output generated by `tsc`. Not sure if typescript offers minification too.

**Comment by kabirbaidhya** [comment]
I realized now why we did webpack before. My bad.
It did generate output like this for the browser 
```js
window.KeyCode=function(E){function _(Y)...
```
Surely, we're going to need rollup.

**Comment by mesaugat** [comment]
I'll send a PR for rollup. You think about using `TypeScript`

**Comment by mesaugat** [comment]
Now we do have a problem. Rollup says `A module cannot import itself.`

**Comment by mesaugat** [comment]
Any other ways to do a default export and a named export? Maybe we need to do something like this: https://github.com/prettymuchbryce/node-http-status/blob/master/index.js

**Comment by mesaugat** [comment]
LOL, Do we even need named exports?

**Comment by kabirbaidhya** [comment]
@mesaugat I think it's not a big deal. Can you try removing that self-importing line and bundle it using rollup? I think it should bundle it as required for the browser. You can check the output if it's usable in the browser.

And for the node, when you transpile it, it generates `lib/` with `module.exports = ` thing. And if you make some tweak in this file https://github.com/kabirbaidhya/keycode-js/blob/master/index.js, I guess, it gives the out the same module as before.

**Comment by mesaugat** [comment]
Oh I forgot about index.js because I removed it. Makes sense, I'll try.
