### ISSUE TITLE
Incompatibility with ES5 (v2.0.1)

### ISSUE THREAD

**Issue by gfx** [kabirbaidhya/keycode-js#30]
Can you use ES modules + ES5 syntax for ESM files? I have to keep my JavaScript project to be compatible with ES5, but there seems no method to do so if I upgrade keycode-js to v2.x.

**Comment by kabirbaidhya** [comment]
@gfx I guess it should just work fine because the built files are plain javascript (es5). Are you using common js module or a script tag? If you're using it like anything mentioned in the [usage](https://github.com/kabirbaidhya/keycode-js#usage), it should work. 

Let us know if you tried and it didn't work.

**Comment by gfx** [comment]
I use keycode-js with webpack4, which refers to the "module" entry in package.json, which is written in ES2015. Of course, I can set an alias to use `keycode.cjs.js`, but it is not tree-shakable. I want a dist file that **uses ES modules and is compatible with ES5**, which seems strange but works well as expected.

**Comment by kabirbaidhya** [comment]
@gfx 
> I use keycode-js with webpack4, which refers to the "module" entry in package.json, which is written in ES2015. Of course, I can set an alias to use keycode.cjs.js, but it is not tree-shakable. I want a dist file that uses ES modules and is compatible with ES5, which seems strange but works well as expected.

Apparently, this is already the case. 
https://github.com/kabirbaidhya/keycode-js/blob/93849c3155493b8544223c041fdc74ae462a3098/package.json#L10-L11

Here, when you do common js require, it should take the common js build as defined in `main` and when you do ES import, it should take ES build via `module`.

> I want a dist file that uses ES modules and is compatible with ES5

I guess this is what you're looking for https://github.com/kabirbaidhya/keycode-js/blob/93849c3155493b8544223c041fdc74ae462a3098/package.json#L11

In case the problem still persists, can you provide what error are you getting?

**Comment by kfeinUI** [comment]
The best practice is generally to have your _main_ be in ES5. Presently, it's ES6 since it's contains _const_. This now requires additional build config to transpile the module.

**Comment by kabirbaidhya** [comment]
Hmm, makes sense. I see the build for main has `const` now which should work perfectly fine with any supported node versions; however, for older browsers it might not - we can make this as a quickfix. 

@gfx Will this fix your issue as well? Not sure if I have understood your problem correctly. 

cc @mesaugat

**Comment by mesaugat** [comment]
Not sure it is anything but related to #31. 

@gfx I've tried using the the library with Webpack 4 and it is working very well. The `module` key and `esm` build look fine. Do you have something that is replicable so that we can take a loot at what you are doing?

**Comment by kabirbaidhya** [comment]
Released - [v2.0.2](https://github.com/kabirbaidhya/keycode-js/releases/tag/v2.0.2). Can you see if this resolves your issue?

**Comment by gfx** [comment]
v2.0.2 works for my project. Thanks for the quick response!

**Comment by gfx** [comment]
Sorry, but v2.0.0 solve only a part of the problems. It still requires webpack configuration to refer .cjs.js because webpack uses `module` field in package.json by default. Otherwise the bundled JS includes the `const` keyword, which is introduced in ES2015 and not compatible with ES5.

I think `.es6.js` should be renamed to `.esm.js` and should be targeted to ES5 (i.e. `"target": "es5", "module": "es2015"` in tsconfig.json).

**Comment by kabirbaidhya** [comment]
@gfx Makes sense. Please feel free to do a PR and we can do another patch. 

I guess rebuilding with a simple change in the rollup config to use typescript plugin (similar to #31) for esm should do it since we already have `target=es5` set in the tsconfig.

**Comment by inspirado** [comment]
@gfx @kabirbaidhya This will be fixed by https://github.com/kabirbaidhya/keycode-js/pull/32

**Comment by kabirbaidhya** [comment]
Thanks @inspirado :+1:

**Comment by kabirbaidhya** [comment]
@gfx Patch released - [v2.0.3](https://github.com/kabirbaidhya/keycode-js/releases/tag/v2.0.3). Feel free to reopen if the issue persists.

**Comment by gfx** [comment]
Thanks! v2.0.3 works perfectly for my production.
