### ISSUE TITLE
Add backticks

### ISSUE THREAD

**Issue by anki247** [kabirbaidhya/keycode-js#34]
Currently there is no const for backticks, which is `keyCode === 229`
backticks(`)

**Comment by kabirbaidhya** [comment]
@anki247 Keycode = `229` isn't precisely the backtick key as you're referring to. And I couldn't find a standard definition of what this keycode defines. 

Don't know what to call it. Could you refer me to a standard list where this is mentioned and as "what" key? 

So, far I inferred it being a sort of placeholder key code, that doesn't mean one particular key.

Here,
* https://stackoverflow.com/questions/25043934/is-it-ok-to-ignore-keydown-events-with-keycode-229/25509350#25509350
* https://lists.w3.org/Archives/Public/www-dom/2010JulSep/att-0182/keyCode-spec.html

**Comment by anki247** [comment]
Yes you are right, it seem that at least mac and windows has different keycode for it 😞
