### ISSUE TITLE
Missing keycodes

### ISSUE THREAD

**Issue by JoshMcCullough** [kabirbaidhya/keycode-js#35]
The following seem to be missing, in addition to backtick which is already mentioned in #34.

On a standard "104 key" keyboard:
- equal/plus -- 187
- hyphen/underscore -- 189

**Comment by kabirbaidhya** [comment]
Yes, looks like it. I'll do a quick patch for it.

**Comment by kabirbaidhya** [comment]
@JoshMcCullough Fixed and published a new version [v3.0.0](https://github.com/kabirbaidhya/keycode-js/releases/tag/v3.0.0). Thanks for reporting!

**Comment by JoshMcCullough** [comment]
Thank you!
