### ISSUE TITLE
Write unit tests to test it returns all the constant keys with correct values

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/keycode-js#4]
Write unit tests to test it returns all the constant keys with correct values

**Comment by ka3work** [comment]
@kabirbaidhya  Hi, I'm a completely new to testing. 
But will this kind of test suffice?
```
it('KEY_CANCEL should return 3', () => {
    assert.equal(KeyCode.KEY_CANCEL, 3);
});
```

I would be happy to help, if this looks alright to you. :smile:

**Comment by kabirbaidhya** [comment]
@frameshft Yes, here we just have simple cases to cover, not much logic; so the purpose is just to verify things work fine in case we do some refactor or change things.
